# This is action publishes the current GitHub Dependabot alerts to a CSV file.

name: Dependabot-Publish-Alerts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  dependabot-alert-export:
    runs-on: ubuntu-latest
    steps:               
      - name: Export Dependabot alerts
        uses: ambilykk/dependabot-alert-export@v1.0
        with:        
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          org_name: 'ORG_NAME'
          repo_name: 'REPO_NAME'
          csv_path: data/vulnerability.csv
          
      - name: Upload Vulnerability report
        uses: actions/upload-artifact@v3
        with:
           name: vulnerability_report
           path: data/vulnerability.csv                 